ENTITY_MAP = [
	[
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
        Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Carrot,
		Entities.Carrot,
	],
	[
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
        Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Carrot,
		Entities.Carrot,
	],
	[
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
        Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Carrot,
		Entities.Carrot,
	],
	[
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
        Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Carrot,
		Entities.Carrot,
	],
	[
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
        Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Carrot,
		Entities.Carrot,
	],
	[
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Pumpkin,
        Entities.Pumpkin,
		Entities.Pumpkin,
		Entities.Carrot,
		Entities.Carrot,
	],
	[
		Entities.Grass,
		Entities.Tree,
		Entities.Grass,
		Entities.Tree,
		Entities.Grass,
		Entities.Tree,
		Entities.Grass,
		Entities.Tree,
	],
	[
		Entities.Tree,
		Entities.Grass,
		Entities.Tree,
		Entities.Grass,
		Entities.Tree,
		Entities.Grass,
		Entities.Tree,
		Entities.Grass,
	]
]

GROUND_MAP = {
    Entities.Bush: [Grounds.Grassland, Grounds.Soil],
    Entities.Cactus: [Grounds.Soil],
    Entities.Carrot: [Grounds.Soil],
    Entities.Dead_Pumpkin: [Grounds.Soil],
    Entities.Grass: [Grounds.Grassland, Grounds.Soil],
    Entities.Pumpkin: [Grounds.Soil],
    Entities.Sunflower: [Grounds.Soil],
    Entities.Tree: [Grounds.Grassland, Grounds.Soil]
}